### ISSUE TITLE
Scan the network and add available worker

### ISSUE THREAD

**Issue by jiajunmao** [Kent-AI-Laboratory/Pseudo-Cluster#16]
**Purpose of this feature**
scan the network and add available worker

**Where should the implementation be added (if applicable)**
com.khpc.headNode, NodeList.java

**Preferred solution**
some file that contains a list of hostname and then ask the DNS server or host file for the corresponding IP address and add the IP address to the NodeList instance

**Additional context (if applicable)**
If better solution is available, please mention

@Kent-AI-Laboratory/developers

**Comment by birkhoffcheng** [comment]
I have an idea, but I don't have anything to work on. After all I only have one machine to work with...

**Comment by jiajunmao** [comment]
@birkhoffcheng will you can always set the send address to the loop back address. But this issue has now been solved, so I am closing the issue
